// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: followed_players.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deletePlayerFollows = `-- name: DeletePlayerFollows :exec
DELETE FROM followed_players
`

func (q *Queries) DeletePlayerFollows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePlayerFollows)
	return err
}

const followPlayer = `-- name: FollowPlayer :one
INSERT INTO followed_players(id, created_at, updated_at, user_id, player_id, player_name)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, user_id, player_id, player_name
`

type FollowPlayerParams struct {
	UserID     uuid.UUID
	PlayerID   int32
	PlayerName string
}

func (q *Queries) FollowPlayer(ctx context.Context, arg FollowPlayerParams) (FollowedPlayer, error) {
	row := q.db.QueryRowContext(ctx, followPlayer, arg.UserID, arg.PlayerID, arg.PlayerName)
	var i FollowedPlayer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PlayerID,
		&i.PlayerName,
	)
	return i, err
}

const getFollowedPlayers = `-- name: GetFollowedPlayers :many
SELECT id, created_at, updated_at, user_id, player_id, player_name FROM followed_players
WHERE user_id = $1
`

func (q *Queries) GetFollowedPlayers(ctx context.Context, userID uuid.UUID) ([]FollowedPlayer, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedPlayers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowedPlayer
	for rows.Next() {
		var i FollowedPlayer
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.PlayerID,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowPlayer = `-- name: UnfollowPlayer :exec
DELETE FROM followed_players
WHERE player_id = $1 AND user_id = $2
`

type UnfollowPlayerParams struct {
	PlayerID int32
	UserID   uuid.UUID
}

func (q *Queries) UnfollowPlayer(ctx context.Context, arg UnfollowPlayerParams) error {
	_, err := q.db.ExecContext(ctx, unfollowPlayer, arg.PlayerID, arg.UserID)
	return err
}
