// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: followed_teams.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteTeamFollows = `-- name: DeleteTeamFollows :exec
DELETE FROM followed_teams
`

func (q *Queries) DeleteTeamFollows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTeamFollows)
	return err
}

const fetchTeamByTriCode = `-- name: FetchTeamByTriCode :one
SELECT id, created_at, updated_at, team_name, tri_code FROM teams 
WHERE tri_code = $1
`

func (q *Queries) FetchTeamByTriCode(ctx context.Context, triCode string) (Team, error) {
	row := q.db.QueryRowContext(ctx, fetchTeamByTriCode, triCode)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamName,
		&i.TriCode,
	)
	return i, err
}

const followTeam = `-- name: FollowTeam :one
INSERT INTO followed_teams(id, created_at, updated_at, team_name, user_id, team_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, team_name, user_id, team_id
`

type FollowTeamParams struct {
	TeamName string
	UserID   uuid.UUID
	TeamID   int32
}

func (q *Queries) FollowTeam(ctx context.Context, arg FollowTeamParams) (FollowedTeam, error) {
	row := q.db.QueryRowContext(ctx, followTeam, arg.TeamName, arg.UserID, arg.TeamID)
	var i FollowedTeam
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamName,
		&i.UserID,
		&i.TeamID,
	)
	return i, err
}

const getFollowedTeam = `-- name: GetFollowedTeam :one
SELECT id, created_at, updated_at, team_name, user_id, team_id FROM followed_teams
WHERE user_id = $1
`

func (q *Queries) GetFollowedTeam(ctx context.Context, userID uuid.UUID) (FollowedTeam, error) {
	row := q.db.QueryRowContext(ctx, getFollowedTeam, userID)
	var i FollowedTeam
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamName,
		&i.UserID,
		&i.TeamID,
	)
	return i, err
}

const unfollowTeam = `-- name: UnfollowTeam :exec
DELETE FROM followed_teams
WHERE user_id = $1 AND team_id = $2
`

type UnfollowTeamParams struct {
	UserID uuid.UUID
	TeamID int32
}

func (q *Queries) UnfollowTeam(ctx context.Context, arg UnfollowTeamParams) error {
	_, err := q.db.ExecContext(ctx, unfollowTeam, arg.UserID, arg.TeamID)
	return err
}
