// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type FollowedPlayer struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.UUID
	PlayerID   int32
	PlayerName string
}

type FollowedTeam struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	TeamName  string
	UserID    uuid.UUID
	TeamID    int32
}

type Player struct {
	ID         int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	PlayerName string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Team struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	TeamName  string
	TriCode   string
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}
