// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package database

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players(id, created_at, updated_at, player_name)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2
)
ON CONFLICT (id) DO UPDATE 
SET player_name = EXCLUDED.player_name, updated_at = NOW()
RETURNING id, created_at, updated_at, player_name
`

type CreatePlayerParams struct {
	ID         int32
	PlayerName string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.ID, arg.PlayerName)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayerName,
	)
	return i, err
}

const deletePlayers = `-- name: DeletePlayers :exec
DELETE FROM players
`

func (q *Queries) DeletePlayers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePlayers)
	return err
}

const fetchPlayerByID = `-- name: FetchPlayerByID :one
SELECT id, created_at, updated_at, player_name FROM players
WHERE id = $1
`

func (q *Queries) FetchPlayerByID(ctx context.Context, id int32) (Player, error) {
	row := q.db.QueryRowContext(ctx, fetchPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayerName,
	)
	return i, err
}
