// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package database

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams(id, created_at, updated_at, team_name, tri_code)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3
)
RETURNING id, created_at, updated_at, team_name, tri_code
`

type CreateTeamParams struct {
	ID       int32
	TeamName string
	TriCode  string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.ID, arg.TeamName, arg.TriCode)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamName,
		&i.TriCode,
	)
	return i, err
}
